name: Deploy Website to Cloudflare Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'website/**'
      - '.github/workflows/pages.yml'
  pull_request:
    paths:
      - 'website/**'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: website/package-lock.json
      - name: Install dependencies
        working-directory: website
        run: npm ci || npm i
      - name: Build
        working-directory: website
        run: npm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: dyad-website
          directory: website/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}